#!/bin/bash

 # Automatizes a git upload, just adds all changes file paths (Any changes, untracked, modified, etc).
 # Mostly useful if you don't care branches or specific files to add, just adding entire changes. 

 $REPO_PATH = "/path/to/your/repo"

 cd $REPO_PATH

 files_paths=()

 git_status=$(git status --porcelain) 

 # Parsing output from git status to get paths.
 while IFS= read -r line; do
 
  file_path=${line:3}

  files_paths+=("$file_path") 
   
 done <<< $git_status 

 if [ ${#files_paths[@]} -eq 0 ]; then 
	 
     exit 1

 fi

 for path in "${files_paths[@]}"; do 

     echo "Added:${path}!" 
     git add "$path" 
 
 done	 

 echo "Commit message:"
 read message

 git commit -m "$message"

 while true; do

 git push origin main

 if [ $? -eq 0  ]; then 

    break

 fi

 done

 git status

